### ISSUE TITLE
View grade statistics

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1353]
_From @steveswinsburg on May 4, 2015 13:3_

**View Grade Statistics**
Opens a lightbox window displaying vital grade stats for the item. This allows the system to calculate the average score on an item-by-item basis. And, since the average would now be appearing in a separate window, this could be a great opportunity to provide additional statistics, such as median/low/high score, as well as maybe standard deviation and a visual histogram.

_Copied from original issue: steveswinsburg/gradebookNG#67_

**Comment by steveswinsburg** [comment]
Stats are in, graph to be added later if still required. @kyleblythe have you got an example of the type of graph you were after?

**Comment by kyleblythe** [comment]
This looks beautiful, @steveswinsburg - thanks!

Quick note re: the current stats - we can probably limit the numbers that are generated to 2 decimal places, as we do with the rest of the GB:

![image](https://cloud.githubusercontent.com/assets/11447474/12819358/bf3e677e-cb28-11e5-9256-54f7a37fa409.png)

Do you think we could also show the percentage score in parentheses following the point value for average, median, lowest, and highest?

And re: the graph - I think it would be useful to provide a bar graph showing distribution of scores for the item. So the x axis is showing the range of scores for the item (e.g., for an item worth 100 pts, you could have demarcations for 0-20, 20-40, 40-60, etc), while the y axis would show the number of students who received scores within a given range. So something like this:

![image](https://cloud.githubusercontent.com/assets/11447474/12819588/a19b245e-cb29-11e5-9868-d0a09e769479.png)

What do you think?

**Comment by steveswinsburg** [comment]
I was thinking we could use JFreeChart for the graphs.

**Comment by payten** [comment]
Hi @kyleblythe.  I started looking at the graph and bumped up against two things:

1) Extra Credit scores or scores greater than the point total.  Would you expect those to be expressed in the graph in the same way?  E.g. if item is out of 10, we create ranges from 0 through to the either the 'out of' value or the maximum score.  Or perhaps an "EC" column at the end as a catch all (if there are any)?

2) As item points are arbitrary, we need to determine the ranges to display on the fly, which might not always be straight forward or offer meaningful intervals e.g if out of 30, this might result in 5 columns with 6point intervals.

We could show percentage values instead.  That way it would be consistent for all grade items and show intervals that won't get weird.  For example, we could show 10 columns at 10% intervals and an extra column for results greater than the total points.  Does that sound reasonable?

**Comment by kyleblythe** [comment]
This sounds great, @payten - I like it! I agree that, since scores are arbitrary, the x-axis range should be percentage-based. As for how many columns display...I'm not sure which would look best, 5 columns at 20% intervals, or 10 columns at 10% intervals. Whichever works best!

And I like this approach to EC. So, if an item has scores above the max points allotted, then an additional column titled "EC" would appear to the far-right as a catch-all for all scores > 100%?

**Comment by kyleblythe** [comment]
Right-o. This looks awesome! I have some feedback:

* Right now, there's a little funkiness with the lightbox window - it's opening a little low in the viewport, and is very wide:

![image](https://cloud.githubusercontent.com/assets/11447474/13505449/36ad91a2-e147-11e5-912b-63746a184934.png)

I think that, ideally, the lightbox frame would have a narrower width, with the same padding on the right as the graph has on the left. It would also open higher in the viewport, so that the "done" button is more easily seen.

Insofar as the graph itself is concerned:

*Maybe we could limit the x-axis ranges to increments of 20%? This will make the graph a little denser, which I think is a good thing.
* Can we make the y-axis a little more condensed? Idk if we need a notch for every integer.
* For markings on the y-axis, can we alternate? So that way you would only see a number for every other entry on the y-axis.
* Can we use a white bg for the graph?
* For some reason, on my computer, the graph is a little...fuzzy (maybe it isn't optimized for retina displays)?

![image](https://cloud.githubusercontent.com/assets/11447474/13505656/ffd9cabe-e147-11e5-88f4-e31d677ec2a3.png)

**Comment by payten** [comment]
Thanks @kyleblythe.  Just a few comments and clarifications:

> Right now, there's a little funkiness with the lightbox window - it's opening a little low in the viewport, and is very wide.

Yep, sounds good. Will try to pull this higher and reduce the width of the modal.  This will be possible if we reduce the number of columns (see below).

> Maybe we could limit the x-axis ranges to increments of 20%? This will make the graph a little denser, which I think is a good thing.

Sure thing.  How about if we created ranges 0-50%, 60-70%, 70-80%, 80-90%, 90-100%? I'm just thinking that 20% increments might be a little coarse and most grades will be above 50% usually (hopefully).

> Can we make the y-axis a little more condensed? Idk if we need a notch for every integer.

By condense, do you mean reduce the height of the graph?  Or retain the current height but have less notches?

> For markings on the y-axis, can we alternate? So that way you would only see a number for every other entry on the y-axis.

Less notches! Maybe... I'll see what we can do.

> Can we use a white bg for the graph?

Yep!

> For some reason, on my computer, the graph is a little...fuzzy (maybe it isn't optimized for retina displays)?

I'm not entirely sure what to do about the fuzziness. The graph is actually an image generated by Sakai's preferred graphing library (http://www.jfree.org/jfreechart/).  I tried creating a larger image and using CSS to make it fit the modal, however this broke the chart tooltips (delivered via an image map with strict pixel coordinates).  We might be stuck with fuzz.  I'll have a play, but I'm not confident!

**Comment by kyleblythe** [comment]
Gorgeous. Words cannot describe my happiness right now. Thanks for this, Payten!

Okay, a few quick last bits:

1) Can we make the " >100" demarcation in the x-axis instead read as "EC"?

![image](https://cloud.githubusercontent.com/assets/11447474/13680797/262903ee-e6c8-11e5-8286-98d2f79f9925.png)


2) Can we apply labels to the axes? So the x-axis reads as "Percentage Scored" and the y-axis reads as "Number of Students"?

3) I'm sorry to be a pain, but now it seems that the lightbox is opening a _little_ too high up on the screen. Could we move it down, say, 150-200 px? Ideally I think the top of the lightbox should line up with the top of the spreadsheet...or maybe just open in the center of the viewport, wherever the user's currently scrolled.

Thanks again!

**Comment by kyleblythe** [comment]
Closing this one out - looks gorgeous!
