### ISSUE TITLE
Additions to Import/Export

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1356]
_From @kyleblythe on June 12, 2015 0:17_

The following are proposed additions to the Import/Export process:

~~__1. Item Selection Screen - Merging of Grade Item and Comments into Single Grouping__
Items and comments are currently displayed as separate importable items on the 2nd Import screen. Merge these together into a single grouping, with line breaks between groupings. The item and comment should still occur on separate lines, with separate statuses associated with each for clarity. Provide only one check-box for each grouping, so that one is importing both the item and its associated comments.~~

__2. Visual Distinction of Update/New Items__
Provide a visual cue making it easier to tell the Updated/New items apart from current "N/A" items (e.g., make "N/A" items styled in a lighter font w/ italics).
__EFFORT:__ low

~~__3. Change "N/A" Item Status to "No Changes"__~~

~~__4. Change "NEW" Status to "New"__~~

~~__5. Remove "N/A" Point Value for Comments__
Leave this field blank.~~

__6. Provide Check-Box Filter to Only Display Updated/New Items__
While the default display on the 2nd Import screen will continue to mirror, in descending order, that of the left-to-right spreadsheet order, provide a check-box filter above the items that will allow users to hide all N/A/No Changes items from the view, effectively showing only Update/New status items.
__EFFORT:__ high

__7. Check the last update date of the imported file and present a warning if it’s older than X days.__
If this is possible, present a warning immediately following upload notifying users that the file has not been updated in x days.
__EFFORT:__ low

__8. Concurrency Check Mechanism__
When grades are being applied we need to use the concurrency check mechanism. The Import code will need to pull the grades and do the comparison. Otherwise you could be setting on the import page for a while, grades could be changed by someone else and then you overwrite the grades with the import. Handle this elegantly, maybe taking the user back to the checkbox page.
__EFFORT:__ medium

__9. Updated Comment Title Format in Downloadable Spreadsheet File and Include Warning on Default Item Creation Page__
Simplify the current comment title format in the GB download file (e.g., */ Week 2 Part */ ) to instead use a single asterisk at the beginning (e.g., * Week 2 Part ). Additionally, provide a warning when user tries to add an asterisk at the beginning of normal item creation via the GB interface, notifying them that this format is reserved exclusively for importing GB comment columns (Note: possibly even in the gradebook service?).
__EFFORT:__ medium

__10. Confirmation Screen - Add Point Total Info__
Provide item point totals on the final confirmation screen, mirroring the info available on item selection screen.
__EFFORT:__ medium

__11. CSV Download - Template Format When GB Does Not Contain Items__
When the Gradebook does not contain any items, the CSV download should instead provide a template for instructors, with a sample item column and sample comments column. If not modified, these sample columns should not be imported when uploading back into the system.
__EFFORT:__ ?

__12. Additional Export Options (to match those available in the "Course Grades" screen of GB1)__
When exporting the GB on the Import / Export screen, provide a text link below the "Download" button entitled "Advanced Options." Selecting this will open a lightbox window that allows users to customize what is included in the export, and select a .pdf export format. The defaults ("Student Name," Student ID," "Gradebook Item Scores" and "Gradebook Item Comments") will be selected and appear at the top. Additional options will be available below, and will include:
* Last Log Date
* Course Grade
* Calculated Course Grade
* Grade Override

(Note that, in GB1, there's also a selectable option for "Points," which will display the total course grade in points. To make this more straightforward, let's have the "Course Grade" option here just export whichever final course grade the instructor's chosen to display for them in the spreadsheet view?)

When any of these options are selected/de-selected and modified from the default, text should be highlighted informing the user that this export can not be imported back into the Gradebook.

Mockup:

![2015-08-19_10-22-12](https://cloud.githubusercontent.com/assets/11447474/9358890/5d0fb5ea-465c-11e5-9d19-dc5126e26f87.png)

__EFFORT:__?

__13. Disable checkbox for items with a status of "No Changes"__
Since no action will occur when selecting "No Changes" items for import, disable the checkboxes for these items.

_Copied from original issue: steveswinsburg/gradebookNG#105_

**Comment by steveswinsburg** [comment]
_From @maurercw on June 23, 2015 3:32_

Are these just wish list items and not bugs that need to be addressed?  I've actually taken care of item 1 already in some refactoring I just did (PR #126).

**Comment by steveswinsburg** [comment]
Hi @maurercw yep you can leave these ones for the time being and we'll get the bugs nailed. Cheers!

**Comment by steveswinsburg** [comment]
Hi @kyleblythe, I've committed a fix for 3,4 and 5 on this list. I can confirm that 1 is implemented too (thanks @maurercw).

To make it easier to see what is outstanding I've edited your original issue and added a strike through for those implemented, plus triaged the other issues to L/M/H effort. Cheers.

**Comment by steveswinsburg** [comment]
_From @kyleblythe on August 19, 2015 14:25_

Updated issue to include requirement for additional export options (as per GB tech call on 8/13).

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I've changed the ordering of these requirements to reflect priority, and have added a few add'l requirements:

**1. Additional Export Options (to match those available in the "Course Grades" screen of GB1)**
When exporting the GB on the Import / Export screen, provide a text link below the "Download" button entitled "Advanced Options." Selecting this will open a lightbox window that allows users to customize what is included in the export, and select a .pdf export format. The defaults ("Student Name," Student ID," "Gradebook Item Scores" and "Gradebook Item Comments") will be selected and appear at the top. Additional options will be available below, and will include:
* Last Log Date
* Course Grade
* Calculated Course Grade
* Grade Override

(Note that, in GB1, there's also a selectable option for "Points," which will display the total course grade in points. To make this more straightforward, let's have the "Course Grade" option here just export whichever final course grade the instructor's chosen to display for them in the spreadsheet view?)

When any of these options are selected/de-selected and modified from the default, text should be highlighted informing the user that this export can not be imported back into the Gradebook.

Mockup:

![image](https://cloud.githubusercontent.com/assets/11447474/14285407/5fe8bb14-fb19-11e5-9d88-ac054a910eaf.png)

**EFFORT:** High
**PRIORITY:** High


**2. Visual Distinction of Update/New Items**
Provide a visual cue making it easier to tell the Updated/New items apart from current "N/A" items (e.g., make "N/A" items styled in a lighter font w/ italics).

**EFFORT:** Low
**PRIORITY:** High

**3. Updated Comment Title Format in Downloadable Spreadsheet File and Include Warning on Default Item Creation Page**
Simplify the current comment title format in the GB download file (e.g., */ Week 2 Part */ ) to instead use a single asterisk at the beginning (e.g., * Week 2 Part ). Additionally, provide a warning when user tries to add an asterisk at the beginning of normal item creation via the GB interface, notifying them that this format is reserved exclusively for importing GB comment columns (Note: possibly even in the gradebook service?).

**EFFORT:** Medium
**PRIORITY:** High

**4. Throw Exception Error When User Tries to Import Comment Column Without Corresponding Item Column**
If the user attempts to import a comment column (e.g., “* Week 3 Homework”) and there is not a matching item column title (either in the uploaded spreadsheet file or already in the Gradebook), provide an error message stating “[x] comment column does not have a corresponding Gradebook item.”

**EFFORT:** ?
**PRIORITY:** High

**5. CSV Download - Template Format When GB Does Not Contain Items**
When the Gradebook does not contain any items, the CSV download should instead provide a template for instructors, with a sample item column and sample comments column. If not modified, these sample columns should not be imported when uploading back into the system.

**EFFORT:** ?
**PRIORITY:** High

**6. Accept New Gradebook Items Without Point Totals**
Currently, the Gradebook requires you to provide point totals for new GB items using the bracket formatting (e.g., [100] ). We should allow for new items to be imported without point totals. If a user provides an item without points (e.g., “Homework 3”), then the “Points” field in the item’s creation page will simply be blank, and the user will be required to enter a point value then.

**EFFORT:** ?
**PRIORITY:** High

**7. Disable checkbox for items with a status of "No Changes"**
Since no action will occur when selecting "No Changes" items for import, disable the checkboxes for these items.

**EFFORT:** ?
**PRIORITY:** Medium

**8. Concurrency Check Mechanism**
When grades are being applied we need to use the concurrency check mechanism. The Import code will need to pull the grades and do the comparison. Otherwise you could be setting on the import page for a while, grades could be changed by someone else and then you overwrite the grades with the import. Handle this elegantly, maybe taking the user back to the checkbox page.

**EFFORT:** Medium
**PRIORITY:** Medium

**9. Trim Leading/Trailing Spaces From Imported Item Titles**
When importing items into the GB, check to see if there are leading/trailing spaces in the item titles. If so, trim these. Accommodate special characters, except for the *, which is used explicitly to designate comments.

Note: GB1 accommodates special characters in item titles.

**EFFORT:** ?
**PRIORITY:** Medium

**10. Confirmation Screen - Add Point Total Info**
Provide item point totals on the final confirmation screen, mirroring the info available on item selection screen.

**EFFORT:** Medium
**PRIORITY:** Low

**11. Check the Last Update Date of the Imported File and Present a Warning if It’s Older Than X Days.**
If this is possible, present a warning immediately following upload notifying users that the file has not been updated in x days.

**EFFORT:** Low
**PRIORITY:** Low

**12. Provide Toggle Filter to Only Display Updated/New Items**
While the default display on the 2nd Import screen will continue to mirror, in descending order, that of the left-to-right spreadsheet order, provide a check-box filter above the items that will allow users to hide all N/A/No Changes items from the view, effectively showing only Update/New status items.

**EFFORT:** High
**PRIORITY:** Low

**Comment by kyleblythe** [comment]
Have separated our the first requirement for this one ("Additional Export Options") into a separate issue, as it is the last bit needed for parity w/ GB1. Also because it is separate from the import process. Have also updated the requirements above to reflect this.

#2686

**Comment by steveswinsburg** [comment]
Need to remove the checkbox if its an external item.

**Comment by payten** [comment]
As discussed, I've created a new issue for ignoring custom export columns in the import process #2796.

**Comment by steveswinsburg** [comment]
4 is done however I have not added the ignore on reimport. If we did that we would have to specify the format and not allow that to be a Gb Item name either.

**Comment by steveswinsburg** [comment]
@kyleblythe just letting you know that all issues are done except the concurrency check feature. I think we should split that into its' own issue as it's a biggy.

**Comment by kyleblythe** [comment]
Create #3300 to account for the last requirement in this issue. Closing this issue out, as all other elements have been accounted for (nice!)
