### ISSUE TITLE
"Display released gradebook items to students" Setting Not Working

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1418]
Deselecting the option for "Display released gradebook items to students" in GB's Settings menu is not providing the expected behavior. When deselected, all Gradebook items should become hidden from the student view, regardless of their individual release settings.

**Comment by steveswinsburg** [comment]
This appears to be a longstanding bug in the gradebook service, since 2009.
The method `getGradesForStudentsForItem` has this line:
`boolean gradeReleased = gradebook.isAssignmentsDisplayed() && gbItem.isReleased();`

but does nothing with it.
This method appears to be unused in the gradebook tool.
Solution is to either fix this API method or handle it in GBNG as well.

**Comment by kyleblythe** [comment]
Confirmed.
