### ISSUE TITLE
Drop Highest/Drop Lowest/Keep Highest Not Working

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1420]
The options for Drop Highest/Drop Lowest/Keep Highest do not appear to be affecting the category subtotal calculations:

E.g., Drop Highest not dropping highest score (as reflected in cat subtotal): http://www.screencast.com/t/cc15prSy

These options should reflect the dropped/kept score in the subtotal calculations, as well as the course grade.

**Comment by steveswinsburg** [comment]
OK the issue here is that `calculateCategoryScore` does not call `applyDropScores` which does the maths. Unfortunately this method takes an `AssignmentGradeRecord` and `calculateCategoryScore` doesn't have this info. 
We will likely need to refactor this code to look the grades up again via:
'Map<String, List<AssignmentGradeRecord>> gradeRecMap = getGradeRecordMapForStudents(session, gradebookId, Collection.singletonList(studentUid));'
for the given student, then call `applyDropScores(gradeRecMap.get(studentUid))` to get the modified list of grade records to parse.

**Comment by steveswinsburg** [comment]
OK this method is done, however the bulk fetch method used in the initial load also needs updating so that we can applyDropScores to it as well.

**Comment by steveswinsburg** [comment]
This should now be resolved, sending the PR.
The course grade should be working correctly already, no change there.
As per the attached screenshot, this student has a course grade of a B+ (score range 87-89 as per the grading schema), which matches the category score of 87.5%, as the category is setup with drop highest. If drop/keep settings weren't being applied correctly, their course grade would be 45/50=90% which would be an A-.

@kyleblythe have you noticed anything specific about the course grade calcs in regards to these settings, or were you just being thorough? :)

<img width="1127" alt="screen shot 2016-01-28 at 12 47 45 am" src="https://cloud.githubusercontent.com/assets/129129/12615398/8b8ed686-c559-11e5-82ef-c28a7920bba1.png">

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

This is all looking great. Thanks! Drop Highest/Lowest and Keep Highest are all working perfectly. And nope, was just being thorough :) The course grade calculation is looking great as well.
