### ISSUE TITLE
Add indication for total number of students

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1580]
This could go next to the group chooser: `Showing 11 of 25 students`.

**Comment by kyleblythe** [comment]
Confirmed.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I'm wondering, actually, if we want to use simpler language when you aren't filtered by section/group. Instead of it saying "Showing 1-17 of 17 students," maybe it could just say "Showing 17 students." And then, once you begin filtering, it could say "Showing 4 our of 17 students."

Also, it looks like the text isn't adjusting when you use the student search filter:

![image](https://cloud.githubusercontent.com/assets/11447474/12827690/dde0ebc2-cb4e-11e5-99b8-7cd1c1896f31.png)

**Comment by payten** [comment]
Currently our pagination has page sizes of 100 rows, so if there are 140 students it reads: `Showing 1 to 100 of 140 students`.

Things we may want to display in this summary:
- the total number of students available to the current user
- the number of students visible on the page
- if paginated, what page are we on and how many pages are there

**A**: So one option might look something like this:

`Showing 100 of 140 students (page 1 of 2)`

As the student column filter hides rows, it may change to:

`Showing 2 of 140 students (page 1 of 2)`

If there is only one page of students (less than 100), then we won't bother showing the `(page 1 of 1)` suffix.

**B**: A little simpler, dropping the total number:

`Showing 100 students (page 1 of 2)`

**C**: Another option could be we keep the Wicket-default summary `Showing 1 to 100 of 140 students` and when the student filter is applied we suffix with `Showing 1 to 100 of 140 students; filtered to 2 students`.


**D**: Ideas?

**Comment by jeffpasch** [comment]
I think we talked about getting rid of 100 page limit? Was just a holdover I think 

----

**Comment by kyleblythe** [comment]
Confirmed!
