### ISSUE TITLE
Grade entry produces error message when value is > 8 characters

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1699]
Numbers in excess of 8 characters produce an error when entered into the GB:

http://www.screencast.com/t/2DGzFDGr

We can provide a hard limit on the number of characters accepted.

Additionally, update the error message that displays at the top of the screen.

**Comment by payten** [comment]
@kyle, @steveswinsburg, I see why this is happening.  The larger numbers when converted to a string are represented in scientific notation e.g. `12345678` becomes `1.2345678E7`.  This then breaks on a rule in the Gradebook service whereby there can only be max two decimal places provided.

So the fix for large integers seems quite straight forward :sun_with_face: 

But another issue presents itself, whereby any scores with more than 2 decimal place (`2.123`) will result in the same error i.e. "An error occurred updating the gradebook item". In this case, perhaps we can:

1. round all user entered scores to two decimal places, or
1. validate max 2 decimal places in GBNG and show the invalid score message if more than 2.  This could be changed to read "Gradebook item score must be a positive number with maximum of 2 decimal places", or
1. pass through the unadulterated decimal-as-a-string `2.123` to the service and let the service handle validation.  Maybe update the error message to read more like the invalid score message "An error occurred updating the gradebook item. Please note, the Gradebook item score must be a positive number with maximum of 2 decimal places".

Any ideas/preferences?

**Comment by steveswinsburg** [comment]
I think the validation should ultimately be on the backend, but we could certainly apply the same to the front end. It sounds like the conversion from the user input is happening too early, ie it shouldn't be going to that format.

**Comment by kyleblythe** [comment]
So this is no longer throwing an error message when you enter a really long score (in fact, it seems to be calculating regardless of length - I was able to generate a massive category subtotal). However, as soon as you then try to go and edit one of these super long scores, you get a concurrent error message:

![image](https://cloud.githubusercontent.com/assets/11447474/13505292/8c4f1cda-e146-11e5-947c-100997f92a25.png)

**Comment by steveswinsburg** [comment]
I think the scientific notation handling also needs to go into the backend where we do concurrent error checks, as I am still getting this:

```
2016-03-04 07:20:27,619 DEBUG http-nio-8080-exec-32 org.sakaiproject.gradebookng.business.GradebookNgBusinessService - storedGrade: *9.9999999999999E13**
2016-03-04 07:20:27,620 DEBUG http-nio-8080-exec-32 org.sakaiproject.gradebookng.business.GradebookNgBusinessService - oldGrade: 99999999999999
2016-03-04 07:20:27,620 DEBUG http-nio-8080-exec-32 org.sakaiproject.gradebookng.business.GradebookNgBusinessService - newGrade: 999999999
```

**Comment by steveswinsburg** [comment]
Modifications merged, ready to re-test :+1:

**Comment by kyleblythe** [comment]
Confirmed!
