### ISSUE TITLE
decimal.setScale return value is ignored

### ISSUE THREAD

**Issue by ottenhoff** [sakaiproject/sakai#1739]
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java

```
decimal.setScale(2, RoundingMode.HALF_DOWN); // same as GradebookService
```

**Comment by steveswinsburg** [comment]
Bah: "Note that since BigDecimal objects are immutable, calls of this method do not result in the original object being modified, contrary to the usual convention of having methods named setX mutate field X. Instead, setScale returns an object with the proper scale; the returned object may or may not be newly allocated."

**Comment by steveswinsburg** [comment]
PR here: #1742
