### ISSUE TITLE
Concurrent editing notifications are not cluster aware

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1840]
I noticed we hadn't recorded this issue yet...

The current mechanism is a polling ajax call that returns a JSON representation of all the changes recorded on the current node by other users.  These concurrent notifications are stored in memory on the node where the changes were made, so a user accessing the gradebook from a different node will not receive these notifications.

**Comment by steveswinsburg** [comment]
This is stored in a cache via the MemoryService which can be setup as a distributed cache per installation. We'd probably have to either use a message queue or database if we wanted something different.

**Comment by payten** [comment]
@kyleblythe, we were seeing some lag in concurrent messages displaying while testing yesterday, so will investigate today before we close and forget this one ;)

**Comment by jonespm** [comment]
Many of the classic Sakai tools use the SAKAI_LOCKS table to lock tables/rows across the cluster. There might be some other ways to do it, but I feel like in the past with Gradebook 1 there was no concurrent editing notification and the second grade would just overwrite the first grade in a cluster.

I don't think many places set up the memory cache right now as distributed because AFIAK you have to setup a secondary server like Terracotta since Hazelcast is not yet implemented (Maybe for Sakai 12 KNL-1272). That would be the best solution for a lot of tools though.

**Comment by jeffpasch** [comment]
note: this can just be pasted in two different browsers

**Comment by jeffpasch** [comment]
Confirmed using two browsers.
