### ISSUE TITLE
Tabbing action no longer works once a score is entered & saved.

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2122]
When a score is entered into the spreadsheet and the tab action is initiated (thereby saving the cell contents), the focus is lost, jumping you back to the top of the screen and preventing you from successfully tabbing through the interface.

Video: http://www.screencast.com/t/S0X9i3bSO

**Comment by payten** [comment]
Ah good catch.  I think this is due to the wicket callback replacing the cell and not retaining the focus for the user... boo.  It feels intuitive to instead change TAB to focus the input to the right (or left when shift is pressed) rather than the menu/flag in the current cell.  This means the focus will leave cell before Wicket has a chance to replace it... :trophy:

This behaviour is in PR 2128.

**Comment by kyleblythe** [comment]
Confirmed.
