### ISSUE TITLE
GradebookNG can't add items in 11.x branch.

### ISSUE THREAD

**Issue by willkara** [sakaiproject/sakai#2278]
Tried creating a GB-NG item  on the 11.x branch and it wouldn't let me. Looks like a bunch of JS errors to me.

![screen shot 2016-04-19 at 15 48 21](https://cloud.githubusercontent.com/assets/3278887/14653540/6a569aba-0647-11e6-91a0-663fb8ec7099.png)
![screen shot 2016-04-19 at 15 48 17](https://cloud.githubusercontent.com/assets/3278887/14653541/6a5764ae-0647-11e6-9b4e-d6c4b58d30e3.png)

**Comment by payten** [comment]
Thanks @willkara.  It looks like the location of jquery-ui.js changed locations and GradebookNG is still referring to the old location.

We'll review all the assets we use and make sure they're up to date.

**Comment by payten** [comment]
Delving deeper, it seems that this issue is isolated to the `11.x` branch and ok on `master`.  More specifically, the `11.x` branch has an older version of GradebookNG (2 months older!) which doesn't contain the patch which fixes this exact issue: caa82ebf7375457426e973c768544f6bb281064c.  

@steveswinsburg, is there anything we can do push through a later version of GradebookNG to the `11.x` branch?

**Comment by steveswinsburg** [comment]
Yeah we are going to ask the branch managers to pull the latest mods into 11.x on a weekly or so basis. So I'm going to close this off. Cheers.
