### ISSUE TITLE
Percentage grade input can sometimes lead to errors

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2736]
Enter grades a few times and eventually a concurrent error may occur due to the conversion of the grades.

**Comment by payten** [comment]
Hi @steveswinsburg, @anishdoshi.  I hit this error and didn't realise there was bug already created and assigned.  If it's useful, here's my patch: https://github.com/sakaiproject/sakai/compare/master...payten:percent-concurrent-error

I think it was due to extra digits when the `oldGrade` was converted to `oldGradeAdjusted` - I was seeing `55.5` become `5.55000000005`.  When this fails to match the storedGrade of `5.55` we get the concurrent error.

**Comment by steveswinsburg** [comment]
I was thinking about this on the way home from work and this was my exact same solution. I also hit this the other day and got `28` vs `28.000000000000004`. 🎉

**Comment by kyleblythe** [comment]
Confirmed - can not produce a concurrent error.
