### ISSUE TITLE
TA Permissions - allow for providing grade/view access to "uncategorized" items

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2956]
@lgekeler found the following issue w/ TA permissions.

Currently, the TA permission rules dropdown for categories allows access to "All Categories" or specific categories. However, the instructor may wish to providing grading access to uncategorized items, which is not currently possible.

Is this something that be easily implemented? Could "Uncategorized" appear as an additional option in this dropdown, beneath the other categories in place?

![image](https://cloud.githubusercontent.com/assets/11447474/16455271/b039f488-3de1-11e6-86cf-73d0562990bf.png)

**Comment by steveswinsburg** [comment]
Ah, interesting case.
Was this an option in Gradebook classique?
Permission are stored against a category. If there is no category then it is the same as 'All Categories'. There would need to be an explicit identifier added for 'Uncategorised' so that it could be added here. If we did that then it shouldn't be too difficult to implement. However the category ID in the DB is a number so we would need to pick an appropriate number that is representative of the category and that cannot be assigned by the service (-1 perhaps).

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

This is not something that's available in GB1, so definitely not a priority. If this is something that could be easily implemented, perhaps we could consider it for 11.1?

**Comment by lgekeler** [comment]
With "All Categories" selected the TA is unable to see the Uncategorized
item...

~LG

Laura Gekeler
LMS Administrator
Teaching and Learning Technologies
Apereo Foundation <https://www.apereo.org/content/projects-communities>
Board '14-2017
University of Notre Dame
Sakai_Team-group@nd.edu

**Comment by steveswinsburg** [comment]
Ok I will fix the bug where all categories hides the uncategorised item.
I'll spin that out into its own issue. Cheers.

sent from my mobile

**Comment by steveswinsburg** [comment]
#2986 should resolve the TA/uncategorised issue.

**Comment by jeffpasch** [comment]
confirmed: http://www.screencast.com/t/JLo4Ymkor
