### ISSUE TITLE
Changing points in a spreadsheet does not get marked as an update 

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3059]
If you export the gradebook, and change the total points from say 100 to 110, then reimport the spreadsheet, the change is not reflected as an update. Should it be? Or should we add info saying that particular change is not supported. If we change the title it becomes an entirely new item.

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

So I think we should aim for parity with GB Classic on this one. If you do change an item's total point value in the csv file and import via the "Import Grades" tab (the one-stop-shop, import-everything approach), changes to the total points get reflected, and don't create new GB items:

Before - item total points in GB Classic:
![image](https://cloud.githubusercontent.com/assets/11447474/16989655/068be0a8-4e63-11e6-8329-1d4fb3a7d27d.png)

Updates to spreadsheet:
![image](https://cloud.githubusercontent.com/assets/11447474/16989687/24f66568-4e63-11e6-84ff-79c69f889896.png)

"Import Grades" confirmation screen:
![image](https://cloud.githubusercontent.com/assets/11447474/16989727/46a74592-4e63-11e6-8a43-0529f1dc486f.png)

After - item total points:
![image](https://cloud.githubusercontent.com/assets/11447474/16989753/5f1a5df8-4e63-11e6-83cf-2ee3985447fc.png)

So I'd say we should allow for total points to be updated. Would this currently be considered a change in the item's title?

**Comment by steveswinsburg** [comment]
The the name and points are different. IIRC it currently only checks the name, hence this inconsistency.

**Comment by jeffpasch** [comment]
This is now picking up the new total points for the item. Nice! :punch::boom::punch:

I noticed that when the total points for an item are changed, the status is "Modified".
![2016-08-07_14-50-57](https://cloud.githubusercontent.com/assets/11447476/17464644/d513f486-5cb1-11e6-84fd-88598871414e.png)

If I update both the total points and the individual scores for an item, the status is also "Modified".  

At the top of the interface we say, "Note: Selecting "Update" items will override existing scores for that item." 

To simplify, I'm wondering if we'd want to use "Update" in both cases and change that text to read, "Note: Selecting "Update" items will override existing values for that item."

Otherwise, folks might be wondering what the difference between Modified and Update is.

Thoughts?

**Comment by payten** [comment]
That makes sense to me.  PR submitted.

**Comment by steveswinsburg** [comment]
'Modified' means the total point value for the assignment has been changed. 'Update' is for the actual data values.

I think instead we should change:
importExport.status.5 = Modified
to
importExport.status.5 = Update

... so that they appear the same in the UI. The difference between the two statuses is an implementation detail but under the hood they do the same thing.

**Comment by steveswinsburg** [comment]
This bulk of this ticket has been merged already so I changed the status on this ticket. But I think we need to figure out what gets displayed here.

**Comment by jeffpasch** [comment]
Modify so that end sees "Update" for both. 

Also update text to read:   Note: Selecting "Update" items will override existing values for that item.

**Comment by kyleblythe** [comment]
Confirmed!
