### ISSUE TITLE
Error on Trunk - In FF, cannot reorder items using "Move Left" / "Move Right" options in item header dropdown.

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3395]
This issue appears to only affect FireFox. To replicate:

1. Within a fresh Gradebook, create 3 GB items.
2. Drag and drop to reorder. Everything works as expected.
3. Now, from the center item, select the item's column header dropdown, and choose to "Move Left" or "Move Right"

Firefox will report a "The page isn't redirecting properly" error. Refreshing does not solve the issue. The URL in the browser contains the following after the tool id:

https://trunk-mysql.nightly.sakaiproject.org/portal/site/c4743672-02cb-4e7c-95ff-f6c11cd253b9/tool/7fa4adf2-97a1-472c-93e0-b795e7fa603b/ **?21-1.ILinkListener-form-table-topToolbars-toolbars-2-headers-5-header-label-menu-moveAssignmentRight**

**Comment by kyleblythe** [comment]
Looks like this issue also occurs when attempting to sort by any category header (again, only in FF). URL string following a sort attempt:

https://trunk-mysql.nightly.sakaiproject.org/portal/site/c4743672-02cb-4e7c-95ff-f6c11cd253b9/tool/7fa4adf2-97a1-472c-93e0-b795e7fa603b/ **?111-1.ILinkListener-form-table-topToolbars-toolbars-2-headers-3-header-label-title**

**Comment by payten** [comment]
Hi @steveswinsburg.  There seems to be some noise on the Wicket forums about this being an issue related to misuse of the `RequestCycleProcessor` which might be likely given some recent changes.  Have you seen this one before?  It's also a little bit strange that this isn't occurring on the  NYU UAT server (both HTTPS and on the latest commits).

**Comment by AnirudhNagulapalli** [comment]
This issue is seen in Chrome too. A blank screen appears when a Gradebook item is moved left/right. On clicking 'back' option of the browser, the page is refreshed and the Gradebook item is moved. If 'refresh' is used on the blank screen and followed by 'back' option, the Gradebook item is move to the left/right twice.
This is only seen in Trunk-mysql. Trunk-Oracle looks fine.

**Comment by steveswinsburg** [comment]
I'm also seeing this when an assignment header is clicked to do the sorting.

**Comment by steveswinsburg** [comment]
Discussed with Payten, this looks similar: https://issues.apache.org/jira/browse/WICKET-6111
I am going to try a Wicket upgrade as the first step.

**Comment by steveswinsburg** [comment]
Marked this as a blocker as it needs to be tested on 11.x to see if its an issue.
Discussed 30/9/2016: Could be the page mounting as / - I might try changing this to /grades so that we don't get a blank Location, could also be the wicket version as this has been found before (WICKET-6111 - thanks @payten for the research on this).

**Comment by kyleblythe** [comment]
Tested in trunk-mysql. Confirmed!

Screencast of FF: http://www.screencast.com/t/LPtvKMZF86uT

**Comment by jonespm** [comment]
Merged to 11.x, thanks
