### ISSUE TITLE
error being written to log when student accesses gradebook with external assignment  

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#4004]
the following error gets generated when a student accesses a gradebook wtih an external assignment: https://gist.github.com/marktriggs/2f4eb07cd9113a4047d908bcaddf02d5

does not seem to be impacting the users, as far as we can tell

**Comment by steveswinsburg** [comment]
This error is actually coming out of Samigo and is because it is casting a String to a Long:

````
public Long getPublishedAssessmentId(String assessmentId) {
    try {
      return PersistenceService.getInstance().
          getPublishedAssessmentFacadeQueries().
          getPublishedAssessmentId(new Long(assessmentId));
    }
    catch (Exception e) {
      log.error(e.getMessage(), e);
      throw new RuntimeException(e);
    }
  }
````
Will need to dig to see what has changed to be passing the assignment reference along. Maybe it was expecting an ID before.

**Comment by steveswinsburg** [comment]
Ok this isn't strictly GradebookNG related but it is interesting. The `GradebookExternalAssessmentServiceImpl#isExternalAssignmentGrouped` method calls every registered external assessment provider to check if the assignment is defined in that tool, and if so, if it is grouped. In the test case I have, I only have assignments in the site, but it is calling Samigo to check.

````
public boolean isExternalAssignmentGrouped(String gradebookUid, String externalId)
		throws GradebookNotFoundException
	{
        // SAK-19668
		final Assignment assignment = getExternalAssignment(gradebookUid, externalId);
		// If we check all available providers for an existing, externally maintained assignment
		// and none manage it, return false since grouping is the outlier case and all items
		// showed for all users until the 2.9 release.
		boolean result = false;
		if (assignment == null) {
            result = false;
            log.info("No assignment found for external assignment check: gradebookUid="+gradebookUid+", externalId="+externalId);
		} else {
	        for (ExternalAssignmentProvider provider : getExternalAssignmentProviders().values()) {
	            if (provider.isAssignmentDefined(externalId)) {
	                result = provider.isAssignmentGrouped(externalId);
	            }
	        }
		}
		return result;
	}
````

In this test case, the reference is:
````
java.lang.NumberFormatException: For input string: "/assignment/a/f70af8fe-eef9-4c5e-a213-0b16e9cdde99/9c2dd739-7a23-43ce-b5e0-afec0128e1a2"
````
Samigo has the code in the earlier comment above where it does the Long conversion, which obviously fails.

The best fix would be to only call the correct provider for the assignment since we know the source of it via the Assignment record, but for now I will get it to catch the NumberFormatException in the GradebookExternalAssessmentServiceImpl

**Comment by kyleblythe** [comment]
Confirmed in trunk: 
![image](https://cloud.githubusercontent.com/assets/11447474/23769115/4b82a28e-04dc-11e7-8b79-36e5eb2fd006.png)
